name: Deploy to Edgeserver.io

on:
  push:
    branches:
      - "main"
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: true
            fetch-depth: 0
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.2
      - name: Build
        run: pnpm build
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@v0.0.34
        with:
          app_id: "178925382399954944"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGE_TOKEN }}
          directory: dist